name: solid

copyright: (c) 2022 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021
default-extensions:
  - DataKinds
  - DeriveAnyClass
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings

ghc-options: -Wall

dependencies:
  - ghc == 9.4.4
  - base == 4.17.0.0
  - bytestring == 0.11.3.1
  - text == 2.0.1
  - filepath == 1.4.2.2
  - directory == 1.3.7.1

build-tools: solid-pp

source-dirs: src

library: {}

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
      - vendor/hspec-hedgehog/src
    dependencies:
      - solid
      - hspec == 2.*

      - hedgehog
      - hspec-core
      - splitmix
      - QuickCheck

      - silently
      - mockery
