name: solid

copyright: (c) 2022-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - DeriveAnyClass
  - DuplicateRecordFields
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings

ghc-options: -Wall -fhide-source-paths

dependencies:
  - haskell-base
  - bytestring
  - text
  - filepath
  - directory
  - containers
  - unix == 2.8.1.0 # remove CPP from src/Env/Raw.hs when >= 2.8.1.1
  - process
  - time

  - solid-pp

build-tools: solid-pp

source-dirs:
  - src
  - import

library:
  when:
    condition: false
    other-modules: Paths_solid

executable:
  main: Main.hs
  source-dirs:
    - driver
    - vendor/cabal-install
  dependencies:
    - solid
    - Cabal
    - cabal-install == 3.10.1.0 # update / remove vendor/Distribution/Client/Main.hs
  when:
    condition: false
    other-modules: Paths_solid

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid
    main: Spec.hs
    source-dirs:
      - test
      - vendor/hspec-hedgehog/src
    dependencies:
      - solid
      - hspec == 2.*

      - hedgehog
      - hspec-core
      - splitmix
      - QuickCheck

      - silently
      - mockery
    when:
      condition: false
      other-modules: Paths_solid
