spec-version: 0.36.0
name: solid

copyright: (c) 2022-2024 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2024

default-extensions:
  - NoImplicitPrelude
  - DeriveAnyClass
  - DuplicateRecordFields
  - LexicalNegation
  - OverloadedRecordDot
  - OverloadedStrings
  - NoFieldSelectors

ghc-options: -Wall -fhide-source-paths -Werror=operator-whitespace

dependencies:
  - haskell-base
  - primitive >= 0.9.1
  - simdutf
  - byteslice
  - bytestring
  - text
  - os-string
  - filepath
  - file-io
  - directory
  - containers
  - unix
  - process
  - time
  - random
  - stm
  - async
  - unliftio-core

  - solid-pp
  - doctest
  - markdown-unlit

build-tools: solid-pp


library:
  source-dirs:
    - src
    - import

executable:
  main: Main.hs
  source-dirs:
    - driver
  dependencies:
    - solid
    - cabal-install >= 3.10.3.0
    - stack >= 3.1.1

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid
    main: Spec.hs
    source-dirs:
      - src
      - import
      - test
    dependencies:
      - hspec == 2.*

      - hedgehog >= 1.5
      - hedgehog-classes
      - hspec-hedgehog >= 0.2
      - hspec-core
      - splitmix
      - QuickCheck

      - silently
      - mockery
      - base64-bytestring
      - temporary
