spec-version: 0.36.0
name: solid

copyright: (c) 2022-2024 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - DeriveAnyClass
  - DuplicateRecordFields
  - LambdaCase
  - LexicalNegation
  - OverloadedRecordDot
  - OverloadedStrings
  - NoFieldSelectors

ghc-options: -Wall -fhide-source-paths -Werror=operator-whitespace

dependencies:
  - haskell-base
  - primitive >= 0.9.1
  - simdutf
  - bytestring
  - text
  - filepath
  - file-io
  - directory
  - containers
  - unix == 2.8.1.0 # remove CPP from src/Env/Raw.hs when >= 2.8.1.1
  - process
  - time
  - random
  - stm
  - async
  - unliftio-core

  - solid-pp
  - doctest
  - markdown-unlit

build-tools: solid-pp


library:
  source-dirs:
    - src
    - import

executable:
  main: Main.hs
  source-dirs:
    - driver
  dependencies:
    - solid
    - Cabal
    - cabal-install >= 3.10.2.1
    - stack >= 2.13.1
    - hpack
    - rio
    - optparse-applicative
    - pantry

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid
    main: Spec.hs
    source-dirs:
      - src
      - import
      - test
      - vendor/hspec-hedgehog/src
    dependencies:
      - hspec == 2.*

      - hedgehog
      - hedgehog-classes
      - hspec-core
      - splitmix
      - QuickCheck

      - silently
      - mockery
      - base64-bytestring
      - temporary
