name: solid

copyright: (c) 2022-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - DeriveAnyClass
  - DuplicateRecordFields
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings

ghc-options: -Wall -fhide-source-paths

dependencies:
  - haskell-base
  - bytestring
  - text
  - filepath
  - file-io
  - directory
  - containers
  - unix == 2.8.1.0 # remove CPP from src/Env/Raw.hs when >= 2.8.1.1
  - process
  - time
  - random
  - stm
  - async
  - unliftio-core

  - solid-pp
  - doctest

build-tools: solid-pp


library:
  source-dirs:
    - src
    - import
  when:
    condition: false
    other-modules: Paths_solid

executable:
  main: Main.hs
  source-dirs:
    - driver
    - vendor/cabal-install
    - vendor/stack-2.11.1/src/main
  dependencies:
    - solid
    - Cabal
    - cabal-install == 3.10.1.0 # update / remove vendor/Distribution/Client/Main.hs
    - stack == 2.11.1
    - hpack
    - rio
    - optparse-applicative == 0.17.0.0
    - pantry >= 0.8.2.2 && < 0.9
  when:
    condition: false
    other-modules: Paths_solid

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid
    main: Spec.hs
    source-dirs:
      - src
      - import
      - test
      - vendor/hspec-hedgehog/src
    dependencies:
      - hspec == 2.*

      - hedgehog
      - hspec-core
      - splitmix
      - QuickCheck

      - silently
      - mockery
      - base64-bytestring
      - temporary
    when:
      condition: false
      other-modules: Paths_solid
