name: haskell-base

copyright: (c) 2023-2024 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

dependencies:
  - base == 4.*

library:
  reexported-modules:
    - Prelude as HaskellPrelude

    - Control.Applicative
    - Control.Arrow
    - Control.Category
    - Control.Concurrent
    - Control.Concurrent.Chan
    - Control.Concurrent.MVar
    - Control.Concurrent.QSem
    - Control.Concurrent.QSemN
    - Control.Exception
    - Control.Exception.Base
    - Control.Monad
    - Control.Monad.Fail
    - Control.Monad.Fix
    - Control.Monad.Instances
    - Control.Monad.IO.Class
    - Control.Monad.ST
    - Control.Monad.ST.Lazy
    - Control.Monad.ST.Lazy.Safe
    - Control.Monad.ST.Lazy.Unsafe
    - Control.Monad.ST.Safe
    - Control.Monad.ST.Strict
    - Control.Monad.ST.Unsafe
    - Control.Monad.Zip
    - Data.Array.Byte
    - Data.Bifoldable
    - Data.Bifoldable1
    - Data.Bifunctor
    - Data.Bitraversable
    - Data.Bits
    - Data.Bool
    - Data.Char
    - Data.Coerce
    - Data.Complex
    - Data.Data
    - Data.Dynamic
    - Data.Either
    - Data.Eq
    - Data.Fixed
    - Data.Foldable
    - Data.Foldable1
    - Data.Function
    - Data.Functor
    - Data.Functor.Classes
    - Data.Functor.Compose
    - Data.Functor.Const
    - Data.Functor.Contravariant
    - Data.Functor.Identity
    - Data.Functor.Product
    - Data.Functor.Sum
    - Data.Int
    - Data.IORef
    - Data.Ix
    - Data.Kind
    - Data.List
    - Data.List.NonEmpty
    - Data.Maybe
    - Data.Monoid
    - Data.Ord
    - Data.Proxy
    - Data.Ratio
    - Data.Semigroup
    - Data.STRef
    - Data.STRef.Lazy
    - Data.STRef.Strict
    - Data.String
    - Data.Traversable
    - Data.Tuple
    - Data.Typeable
    - Data.Type.Bool
    - Data.Type.Coercion
    - Data.Type.Equality
    - Data.Type.Ord
    - Data.Unique
    - Data.Version
    - Data.Void
    - Data.Word
    - Debug.Trace
    - Foreign
    - Foreign.C
    - Foreign.C.ConstPtr
    - Foreign.C.Error
    - Foreign.Concurrent
    - Foreign.C.String
    - Foreign.C.Types
    - Foreign.ForeignPtr
    - Foreign.ForeignPtr.Safe
    - Foreign.ForeignPtr.Unsafe
    - Foreign.Marshal
    - Foreign.Marshal.Alloc
    - Foreign.Marshal.Array
    - Foreign.Marshal.Error
    - Foreign.Marshal.Pool
    - Foreign.Marshal.Safe
    - Foreign.Marshal.Unsafe
    - Foreign.Marshal.Utils
    - Foreign.Ptr
    - Foreign.Safe
    - Foreign.StablePtr
    - Foreign.Storable
    - GHC.Arr
    - GHC.ArrayArray
    - GHC.Base
    - GHC.Bits
    - GHC.ByteOrder
    - GHC.Char
    - GHC.Clock
    - GHC.Conc
    - GHC.Conc.IO
    - GHC.Conc.Signal
    - GHC.Conc.Sync
    - GHC.ConsoleHandler
    - GHC.Constants
    - GHC.Desugar
    - GHC.Encoding.UTF8
    - GHC.Enum
    - GHC.Environment
    - GHC.Err
    - GHC.Event
    - GHC.Event.TimeOut
    - GHC.Exception
    - GHC.Exception.Type
    - GHC.ExecutionStack
    - GHC.ExecutionStack.Internal
    - GHC.Exts
    - GHC.Fingerprint
    - GHC.Fingerprint.Type
    - GHC.Float
    - GHC.Float.ConversionUtils
    - GHC.Float.RealFracMethods
    - GHC.Foreign
    - GHC.ForeignPtr
    - GHC.Generics
    - GHC.GHCi
    - GHC.GHCi.Helpers
    - GHC.InfoProv
    - GHC.Int
    - GHC.Integer
    - GHC.Integer.Logarithms
    - GHC.IO
    - GHC.IOArray
    - GHC.IO.Buffer
    - GHC.IO.BufferedIO
    - GHC.IO.Device
    - GHC.IO.Encoding
    - GHC.IO.Encoding.CodePage
    - GHC.IO.Encoding.Failure
    - GHC.IO.Encoding.Iconv
    - GHC.IO.Encoding.Latin1
    - GHC.IO.Encoding.Types
    - GHC.IO.Encoding.UTF16
    - GHC.IO.Encoding.UTF32
    - GHC.IO.Encoding.UTF8
    - GHC.IO.Exception
    - GHC.IO.FD
    - GHC.IO.Handle
    - GHC.IO.Handle.FD
    - GHC.IO.Handle.Internals
    - GHC.IO.Handle.Lock
    - GHC.IO.Handle.Text
    - GHC.IO.Handle.Types
    - GHC.IO.IOMode
    - GHC.IOPort
    - GHC.IORef
    - GHC.IO.StdHandles
    - GHC.IO.SubSystem
    - GHC.IO.Unsafe
    - GHC.IsList
    - GHC.Ix
    - GHC.List
    - GHC.Maybe
    - GHC.MVar
    - GHC.Natural
    - GHC.Num
    - GHC.Num.BigNat
    - GHC.Num.Integer
    - GHC.Num.Natural
    - GHC.OldList
    - GHC.OverloadedLabels
    - GHC.Pack
    - GHC.Profiling
    - GHC.Ptr
    - GHC.Read
    - GHC.Real
    - GHC.Records
    - GHC.ResponseFile
    - GHC.RTS.Flags
    - GHC.Show
    - GHC.ST
    - GHC.Stable
    - GHC.StableName
    - GHC.Stack
    - GHC.Stack.CCS
    - GHC.Stack.CloneStack
    - GHC.Stack.Types
    - GHC.StaticPtr
    - GHC.Stats
    - GHC.Storable
    - GHC.STRef
    - GHC.TopHandler
    - GHC.TypeError
    - GHC.TypeLits
    - GHC.TypeLits.Internal
    - GHC.TypeNats
    - GHC.TypeNats.Internal
    - GHC.Unicode
    - GHC.Weak
    - GHC.Weak.Finalize
    - GHC.Word
    - Numeric
    - Numeric.Natural
    - System.Console.GetOpt
    - System.CPUTime
    - System.Environment
    - System.Environment.Blank
    - System.Exit
    - System.Info
    - System.IO
    - System.IO.Error
    - System.IO.Unsafe
    - System.Mem
    - System.Mem.StableName
    - System.Mem.Weak
    - System.Posix.Internals
    - System.Posix.Types
    - System.Timeout
    - Text.ParserCombinators.ReadP
    - Text.ParserCombinators.ReadPrec
    - Text.Printf
    - Text.Read
    - Text.Read.Lex
    - Text.Show
    - Text.Show.Functions
    - Type.Reflection
    - Type.Reflection.Unsafe
    - Unsafe.Coerce
