name: solid-pp

copyright: (c) 2022-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

default-extensions:
 - DataKinds
 - OverloadedRecordDot
 - LambdaCase

ghc-options: -Wall

dependencies:
  - base == 4.*
  - array
  - ghc == 9.6.2

  - containers
  - transformers
  - ghc-boot
  - text
  - bytestring

build-tools: alex

library:
  source-dirs:
    - src
    - vendor

executable:
  main: driver/Main.hs
  dependencies:
    - solid-pp

tests:
  spec:
    cpp-options: -DTEST
    build-tools:
      - hspec-discover
      - solid-pp
    main: Spec.hs
    source-dirs:
      - src
      - vendor
      - test
    dependencies:
      - hspec == 2.*
      - hspec-expectations >= 0.8.3
      - HUnit
      - mockery
