name: solid-pp

copyright: (c) 2022 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

ghc-options: -Wall

dependencies:
  - base == 4.*
  - ghc == 9.4.2

library:
  source-dirs: src
  dependencies:
    - containers
    - transformers
    - ghc-boot
    - text
    - bytestring

executable:
  main: driver/Main.hs
  dependencies:
    - solid-pp

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid-pp
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - solid-pp
      - hspec == 2.*
      - mockery
