name: solid-pp

copyright: (c) 2022-2024 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2024

default-extensions:
 - OverloadedRecordDot

ghc-options: -Wall

dependencies:
  - base == 4.*
  - array
  - ghc == 9.10.1

  - containers
  - transformers
  - ghc-boot
  - text
  - bytestring
  - megaparsec >= 9.7.0
  - parser-combinators

build-tools: alex

library:
  source-dirs:
    - src
    - vendor

executable:
  main: driver/Main.hs
  dependencies:
    - solid-pp

tests:
  spec:
    cpp-options: -DTEST
    build-tools:
      - hspec-discover
      - solid-pp
    main: Spec.hs
    source-dirs:
      - src
      - vendor
      - test
    dependencies:
      - hspec == 2.*
      - hspec-expectations >= 0.8.3
      - call-stack
      - HUnit
      - mockery
      - process
      - temporary
      - filepath

