name: solid-pp

copyright: (c) 2022-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

language: GHC2021

default-extensions:
 - DataKinds
 - OverloadedRecordDot
 - LambdaCase

ghc-options: -Wall

dependencies:
  - base == 4.*
  - array
  - ghc == 9.6.1

build-tools: alex

library:
  source-dirs:
    - src
    - vendor
  dependencies:
    - containers
    - transformers
    - ghc-boot
    - text
    - bytestring

executable:
  main: driver/Main.hs
  dependencies:
    - solid-pp

tests:
  spec:
    build-tools:
      - hspec-discover
      - solid-pp
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - solid-pp
      - hspec == 2.*
      - mockery
