name: arcade
copyright: (c) 2023 Simon Hengel

defaults:
  local: ../.hpack/defaults.yaml

ghc-options: -Wall

dependencies:
  - solid-pp
  - haskell-base
  - containers
  - unix
  - text-rope

  - attoparsec
  - text
  - aeson
  - directory
  - yaml
  - ghc
  - logging-facade
  - process
  - transformers

source-dirs: src

executable:
  main: Arcade.main

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      # - QuickCheck
      - interpolate
